server:
  port: 8082

spring:
  application:
    name: converter-json

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5